blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/anthony-liddle/contact-your-reps/issues/new
    about: Ask a question about using or contributing to this project
